language: ruby
rvm:
  - 2.5.1
before_script:
  - gem install bundler
  - bundle update
  - bundle install
  - bundle exec rake db:reset
script:
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/ -fd --order rand
